<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-H9CG5VC" ignored="2" name="Test" tests="7" failures="3" timestamp="2022-05-19T23:54:55 IST" time="5.489" errors="0">
  <testcase name="deleteCustomer" time="3.733" classname="com.albertsons.APITestingFramework.testcases.DeleteCustomerTest">
    <failure type="java.lang.AssertionError" message="id key is not present in json response expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: id key is not present in json response expected [true] but found [false]
at com.albertsons.APITestingFramework.testcases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:35)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase name="deleteCustomer" time="3.733" classname="com.albertsons.APITestingFramework.testcases.DeleteCustomerTest">
    <failure type="java.lang.AssertionError" message="id key is not present in json response expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: id key is not present in json response expected [true] but found [false]
at com.albertsons.APITestingFramework.testcases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:35)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase name="deleteCustomer" time="3.733" classname="com.albertsons.APITestingFramework.testcases.DeleteCustomerTest">
    <failure type="java.lang.AssertionError" message="id key is not present in json response expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: id key is not present in json response expected [true] but found [false]
at com.albertsons.APITestingFramework.testcases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:35)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase name="validateCreateCustomerApiWithInvalidSecretKey" time="0.747" classname="com.albertsons.APITestingFramework.testcases.CreateCustomerTest"/>
  <testcase name="validateCreateCustomerApiWithValidSecretKey" time="0.827" classname="com.albertsons.APITestingFramework.testcases.CreateCustomerTest"/>
  <testcase name="validateCreateCustomerApiWithValidSecretKey" time="0.861" classname="com.albertsons.APITestingFramework.testcases.CreateCustomerTest"/>
  <testcase name="validateCreateCustomerApiWithValidSecretKey" time="0.872" classname="com.albertsons.APITestingFramework.testcases.CreateCustomerTest"/>
  <testcase name="@BeforeSuite setUp" time="0.0" classname="com.albertsons.ApiFramework.setup.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite setUp -->
  <testcase name="@AfterSuite tearDown" time="0.0" classname="com.albertsons.ApiFramework.setup.BaseTest">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
</testsuite> <!-- Test -->
