<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="2" total="8" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="5773" started-at="2022-05-21T13:07:49 IST" finished-at="2022-05-21T13:07:55 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="5773" started-at="2022-05-21T13:07:49 IST" finished-at="2022-05-21T13:07:55 IST">
      <class name="com.albertsons.APITestingFramework.testcases.CreateCustomerTest">
        <test-method status="PASS" signature="validateCreateCustomerApiWithInvalidSecretKey(java.util.Hashtable)[pri:0, instance:com.albertsons.APITestingFramework.testcases.CreateCustomerTest@2f217633]" name="validateCreateCustomerApiWithInvalidSecretKey" duration-ms="662" started-at="2022-05-21T13:07:53 IST" data-provider="data" finished-at="2022-05-21T13:07:53 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=barik.pradyumn0@gmail.com, name=pradyumn, description=this is the first api}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerApiWithInvalidSecretKey -->
        <test-method status="PASS" signature="validateCreateCustomerApiWithValidSecretKey(java.util.Hashtable)[pri:0, instance:com.albertsons.APITestingFramework.testcases.CreateCustomerTest@2f217633]" name="validateCreateCustomerApiWithValidSecretKey" duration-ms="1178" started-at="2022-05-21T13:07:53 IST" data-provider="data" finished-at="2022-05-21T13:07:55 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=barik.pradyumn0@gmail.com, name=pradyumn, description=this is the first api}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerApiWithValidSecretKey -->
        <test-method status="PASS" signature="validateCreateCustomerApiWithValidSecretKey(java.util.Hashtable)[pri:0, instance:com.albertsons.APITestingFramework.testcases.CreateCustomerTest@2f217633]" name="validateCreateCustomerApiWithValidSecretKey" duration-ms="1066" started-at="2022-05-21T13:07:53 IST" data-provider="data" finished-at="2022-05-21T13:07:54 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=swati.sinha@gmail.com, name=swati, description=this is the third api}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerApiWithValidSecretKey -->
        <test-method status="PASS" signature="validateCreateCustomerApiWithValidSecretKey(java.util.Hashtable)[pri:0, instance:com.albertsons.APITestingFramework.testcases.CreateCustomerTest@2f217633]" name="validateCreateCustomerApiWithValidSecretKey" duration-ms="1083" started-at="2022-05-21T13:07:53 IST" data-provider="data" finished-at="2022-05-21T13:07:54 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=kanha.prusti@gmail.com, name=kanha, description=this is the second api}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerApiWithValidSecretKey -->
      </class> <!-- com.albertsons.APITestingFramework.testcases.CreateCustomerTest -->
      <class name="com.albertsons.APITestingFramework.testcases.DeleteCustomerTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.albertsons.APITestingFramework.testcases.DeleteCustomerTest@22ef9844]" name="setUp" is-config="true" duration-ms="750" started-at="2022-05-21T13:07:48 IST" finished-at="2022-05-21T13:07:49 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="deleteCustomer(java.util.Hashtable)[pri:0, instance:com.albertsons.APITestingFramework.testcases.DeleteCustomerTest@22ef9844]" name="deleteCustomer" duration-ms="3788" started-at="2022-05-21T13:07:49 IST" data-provider="data" finished-at="2022-05-21T13:07:53 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{id=cus_LjEkKtVJFmOveF}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[id key is not present in json response expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: id key is not present in json response expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.albertsons.APITestingFramework.testcases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteCustomer -->
        <test-method status="FAIL" signature="deleteCustomer(java.util.Hashtable)[pri:0, instance:com.albertsons.APITestingFramework.testcases.DeleteCustomerTest@22ef9844]" name="deleteCustomer" duration-ms="3788" started-at="2022-05-21T13:07:49 IST" data-provider="data" finished-at="2022-05-21T13:07:53 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{id=cus_LjEkWXVHwvpIBU}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[id key is not present in json response expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: id key is not present in json response expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.albertsons.APITestingFramework.testcases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteCustomer -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.albertsons.APITestingFramework.testcases.DeleteCustomerTest@22ef9844]" name="tearDown" is-config="true" duration-ms="1" started-at="2022-05-21T13:07:55 IST" finished-at="2022-05-21T13:07:55 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.albertsons.APITestingFramework.testcases.DeleteCustomerTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
